---    Create schema  ----
CREATE SCHEMA gbdx_metadata;

---  Create table: metadata ---
CREATE TABLE gbdx_metadata.sat_imagery_meta (
	_unnamed INTEGER NOT NULL,
	bearing VARCHAR(32),
	browseurl VARCHAR(69) NOT NULL,
	catalogid VARCHAR(16) NOT NULL,
	cloudcover INTEGER NOT NULL,
	footprintwkt GEOMETRY(MULTIPOLYGON) NOT NULL,
	imagebands VARCHAR(11) NOT NULL,
	multiresolution FLOAT,
	multiresolution_end FLOAT,
	multiresolution_max FLOAT,
	multiresolution_min FLOAT,
	multiresolution_start FLOAT,
	offnadirangle FLOAT NOT NULL,
	offnadirangle_end FLOAT NOT NULL,
	offnadirangle_max FLOAT NOT NULL,
	offnadirangle_min FLOAT NOT NULL,
	offnadirangle_start FLOAT NOT NULL,
	panresolution FLOAT,
	panresolution_end FLOAT,
	panresolution_max FLOAT,
	panresolution_min FLOAT,
	panresolution_start FLOAT,
	platformname VARCHAR(16) NOT NULL,
	scandirection VARCHAR(7) NOT NULL,
	sensorplatformname VARCHAR(16) NOT NULL,
	stereopair VARCHAR(32),
	sunazimuth FLOAT NOT NULL,
	sunazimuth_max FLOAT NOT NULL,
	sunazimuth_min FLOAT NOT NULL,
	sunelevation FLOAT NOT NULL,
	sunelevation_max FLOAT NOT NULL,
	sunelevation_min FLOAT NOT NULL,
	targetazimuth FLOAT NOT NULL,
	targetazimuth_end FLOAT NOT NULL,
	targetazimuth_max FLOAT NOT NULL,
	targetazimuth_min FLOAT NOT NULL,
	targetazimuth_start FLOAT NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	vendor VARCHAR(12) NOT NULL,
	date DATE NOT NULL,
	day INTEGER NOT NULL,
	month INTEGER NOT NULL,
	hour INTEGER NOT NULL,
	minute INTEGER NOT NULL,
	second INTEGER NOT NULL
);

